# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'PushKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'AVOSCloud' , '~> 8.0.4'
     pod 'AVOSCloudIM', '~> 8.0.4'
     
end
